STS/Models/Shipment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STS.Models
{
    public class Shipment
    {
        [Key]
        public string TrackingNumber { set; get; }
        [StringLength(90)]
        public string SenderName{ set; get; }
        [Phone]
        public string SenderPhoneNumber { set; get; }
        [StringLength(90)]
        public string ReceiverName { set; get; }
        [Phone]
        public string ReceiverPhoneNumber { set; get; }
        public float WeightKG { set; get; }
        [StringLength(255)]
        public string Description { set; get; }
        public DateTime DateAdded { set; get; }
        public DateTime ArrivalDate { set; get; }
        public byte Status { set; get; }
        public Location CurrentLocation { set; get; }
        public Location Source { set; get; }
        public Location Destination { set; get; }
        public byte CollectionMethod { set; get; }
        public double DeliveryLocationLatitude { set; get; }
        public double DeliveryLocationlongitude { set; get; }
    }
}

STS/ViewModels/ShipmentsViewModels.cs
using STS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace STS.ViewModels
{
    public class ShipmentFormViewModel
    {
        public IEnumerable<SelectListItem> Locations { get; set; }
        public IEnumerable<SelectListItem> CollectionMethods { get; set; }
        public string TrackingNumber { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [StringLength(90, ErrorMessageResourceName = "StringLength", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "SenderName", ResourceType = typeof(Resources.Views.Shipments))]
        public string SenderName { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Phone(ErrorMessageResourceName = "IsPhone", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "SenderPhoneNumber", ResourceType = typeof(Resources.Views.Shipments))]
        public string SenderPhoneNumber { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [StringLength(90, ErrorMessageResourceName = "StringLength", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "ReceiverName", ResourceType = typeof(Resources.Views.Shipments))]
        public string ReceiverName { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Phone(ErrorMessageResourceName = "IsPhone", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "ReceiverPhoneNumber", ResourceType = typeof(Resources.Views.Shipments))]
        public string ReceiverPhoneNumber { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "WeightKG", ResourceType = typeof(Resources.Views.Shipments))]
        public float WeightKG { set; get; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [StringLength(255, ErrorMessageResourceName = "StringLength", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "Description", ResourceType = typeof(Resources.Views.Shipments))]
        public string Description { set; get; }
        [Required(ErrorMessageResourceName = "DestinationRequired", ErrorMessageResourceType = typeof(Resources.Views.Shipments))]
        [Display(Name = "Destination", ResourceType = typeof(Resources.Views.Shipments))]
        public int DestinationLocationId { get; set; }
        [Display(Name = "CollectionMethod", ResourceType = typeof(Resources.Views.Shipments))]
        public byte CollectionMethod { get; set; }
    }

    public class ShipmentDetailsViewModel
    {
        [Display(Name = "TrackingNumber", ResourceType = typeof(Resources.Views.Shipments))]
        public string TrackingNumber { set; get; }
        [Display(Name = "SenderName", ResourceType = typeof(Resources.Views.Shipments))]
        public string SenderName { set; get; }
        [Display(Name = "SenderPhoneNumber", ResourceType = typeof(Resources.Views.Shipments))]
        public string SenderPhoneNumber { set; get; }
        [Display(Name = "ReceiverName", ResourceType = typeof(Resources.Views.Shipments))]
        public string ReceiverName { set; get; }
        [Display(Name = "ReceiverPhoneNumber", ResourceType = typeof(Resources.Views.Shipments))]
        public string ReceiverPhoneNumber { set; get; }
        [Display(Name = "WeightKG", ResourceType = typeof(Resources.Views.Shipments))]
        public string WeightKG { set; get; }
        [Display(Name = "Description", ResourceType = typeof(Resources.Views.Shipments))]
        public string Description { set; get; }
        [Display(Name = "DateAdded", ResourceType = typeof(Resources.Views.Shipments))]
        public string DateAdded { set; get; }
        [Display(Name = "Source", ResourceType = typeof(Resources.Views.Shipments))]
        public string Source { set; get; }
        [Display(Name = "Destination", ResourceType = typeof(Resources.Views.Shipments))]
        public string Destination { set; get; }
        [Display(Name = "ArrivalDate", ResourceType = typeof(Resources.Views.Shipments))]
        public string ArrivalDate { set; get; }
        [Display(Name = "CollectionMethod", ResourceType = typeof(Resources.Views.Shipments))]
        public string CollectionMethod { get; set; }
        [Display(Name = "DeliveryLocation", ResourceType = typeof(Resources.Views.Shipments))]
        public string DeliveryLocationUrl { set; get; }
    }
}

STS/Controllers/Operations-api/ShipmentsController.cs
using STS.Dtos;
using STS.Models;
using System.Web.Http;
using System.Data.Entity;
using System.Linq;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using STS.Resources.Api;

namespace STS.Controllers.Operations_api
{
    [Authorize(Roles = "Employee")]
    public class ShipmentsController : ApiController
    {
        private ApplicationDbContext DbContext;

        public ShipmentsController()
        {
            DbContext = ApplicationDbContext.Create();
        }

        [HttpPost]
        [Route("Operations-api/Shipments/{TrackingNumber}")]
        public IHttpActionResult Departed(string TrackingNumber)
        {
            var Shipment = GetShipmentByTrackingNumber(TrackingNumber);
            if (IsExist(Shipment))
            {
                if(SameLocation(Shipment , GetEmployeeInformation(User.Identity.GetUserId())) && IsWaitingShipping(Shipment))
                {
                    DbContext.Reports.Add(GenerateReport(Shipment, Event.Departed));
                    Shipment.CurrentLocation = null;
                    Shipment.Status = (byte)Status.Shipping;
                    DbContext.SaveChanges();
                    return Ok(Shipments.ShipmentOperationSuccess);
                }
                return BadRequest(Shipments.DifferentLocation);
            }
            return NotFound();
     }

        [HttpPost]
        [Route("Operations-api/Shipments/Collected/{TrackingNumber}")]
        public IHttpActionResult Collected(string TrackingNumber , string CollectorName)
        {
            var Shipment = GetShipmentByTrackingNumber(TrackingNumber);
            if (IsExist(Shipment))
            {
                if (SameLocation(Shipment, GetEmployeeInformation(User.Identity.GetUserId())) && IsWaitingCollection(Shipment))
                {
                        DbContext.Reports.Add(GenerateReport(Shipment, Event.Collected, CollectorName));
                        Shipment.CurrentLocation = null;
                        Shipment.Status = (byte)Status.Collected;
                        DbContext.SaveChanges();
                        return Ok(Shipments.ShipmentOperationSuccess);
                }
                return BadRequest(Shipments.DifferentLocation);
            }
            return NotFound();
        }


        [HttpGet]
        [Route("Operations-api/Shipments/Arrived/{TrackingNumber}")]
        public IHttpActionResult Preview(string TrackingNumber)
        {
            var Shipment = GetShipmentByTrackingNumber(TrackingNumber);
            if (IsExist(Shipment))
            {
                if(IsShipping(Shipment))
                {
                    return Ok(GetShipmentPreviewData(Shipment));
                }
                 return BadRequest(Shipments.IsNotShipping);
             }
            return NotFound();
        }


        [HttpPost]
        [Route("Operations-api/Shipments/Arrived/{TrackingNumber}")]
        public IHttpActionResult Arrived(string TrackingNumber)
        {
            var Shipment = GetShipmentByTrackingNumber(TrackingNumber);
            if (IsExist(Shipment))
            {
                if (IsShipping(Shipment))
                {
                    var EmployeeLocation = GetEmployeeLocation(User.Identity.GetUserId());
                    Shipment.CurrentLocation = EmployeeLocation;
                    Shipment.ArrivalDate = DateTime.Now;
                    Shipment.Status = (byte)UpdateArrivedShipmentStatus(Shipment, EmployeeLocation);
                    DbContext.Reports.Add(GenerateReport(Shipment , Event.Arrived));
                    if (IsWaitingCollection(Shipment) && Shipment.CollectionMethod == (byte)CollectionMethod.Pickup)
                    {
                        DbContext.Reports.Add(GenerateReport(Shipment, Event.WaitingCollection));
                    }
                    DbContext.SaveChanges();
                    SendSMS(Shipment);
                    return Ok(Shipments.ShipmentOperationSuccess);
                }
                return BadRequest(Shipments.IsNotShipping);
            }
            return NotFound();
        }

        

        #region Helpers

        private void SendSMS(Shipment shipment)
        {
            switch ((CollectionMethod)shipment.CollectionMethod)
            {
                case CollectionMethod.Pickup : SendPickUpSMS(shipment); break;
                case CollectionMethod.Delivery : SendDeliverySMS(shipment); break;
            }
        }

        private void SendDeliverySMS(Shipment shipment)
        {
            
        }

        private void SendPickUpSMS(Shipment shipment)
        {
            
        }

        private Shipment GetShipmentByTrackingNumber(string TrackingNumber)
        {
            return DbContext.Shipments.Include(Shipment => Shipment.Source).Include(Shipment => Shipment.CurrentLocation).Include(Shipment => Shipment.Destination).SingleOrDefault(Shipment => Shipment.TrackingNumber == TrackingNumber);
        }

        private bool IsExist(Shipment Shipment)
        {
            return Shipment != null;
        }

        private bool SameLocation(Shipment Shipment , ApplicationUser ApplicationUser)
        {
            return Shipment.CurrentLocation.Id == ApplicationUser.EmployeeLocationId;
        }

        private ApplicationUser GetEmployeeInformation(String UserId)
        {
            return new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(DbContext)).FindById(UserId);
        }

        private Report GenerateReport(Shipment Shipment, Event Event, string CollectorName = null)
        {
            var Report = new Report
            {
                Shipment = Shipment,
                Location = Shipment.CurrentLocation,
                DateTime = DateTime.Now,
                Event = (byte)Event
            };
            if (Event == Event.Collected)
            {
                Report.SignedBy = CollectorName;
            }
            return Report;
        }

        private bool IsShipping(Shipment Shipment)
        {
            return Shipment.Status == (byte)Status.Shipping;
        }

        public static string LocationToString(Location Location)
        {
            return Location.City.ToString() + " - " + Location.LocationName.ToString();
        }

        private ShipmentDto GetShipmentPreviewData(Shipment Shipment)
        {
            var ShipmentPreviewData = new ShipmentDto
            {
                TrackingNumber = Shipment.TrackingNumber,
                ReceiverName = Shipment.ReceiverName,
                Destination = LocationToString(Shipment.Destination),
                Status = StatusToString((Status)Shipment.Status)
            };
            return ShipmentPreviewData;
        }

        private Location GetEmployeeLocation(string UserId)
        {
            var EmployeeLocationId = GetEmployeeInformation(UserId).EmployeeLocationId;
            return DbContext.Locations.SingleOrDefault(Location => Location.Id == EmployeeLocationId);
        }

        private Status UpdateArrivedShipmentStatus(Shipment Shipment , Location EmployeeLocation)
        {
            Shipment.DeliveryLocationLatitude = 0;
            Shipment.DeliveryLocationlongitude = 0;
            return EmployeeLocation == Shipment.Destination ? Status.WaitingCollection : Status.WaitingShipping;
        }

        private bool IsWaitingCollection(Shipment Shipment)
        {
            return Shipment.Status == (byte)Status.WaitingCollection;
        }

        private bool IsWaitingShipping(Shipment Shipment)
        {
            return Shipment.Status == (byte)Status.WaitingShipping;
        }

        private string StatusToString(Status Status)
        {
            switch (Status)
            {
                case Status.WaitingShipping:
                    return Resources.Views.Shipments.ShipmentWaitingShipping;
                case Status.Shipping:
                    return Resources.Views.Shipments.ShipmentShipping;
                case Status.WaitingCollection:
                    return Resources.Views.Shipments.ShipmentWaitingCollection;
                case Status.Collected:
                    return Resources.Views.Shipments.ShipmentCollected;
                default:
                    return null;
            }
        }

        enum Status
        {
            WaitingShipping,
            Shipping,
            WaitingCollection,
            Collected
        }

        enum Event
        {
            Registered,
            Departed,
            Arrived,
            WaitingCollection,
            Collected,
            Updated,
            NewDeliverylocation
        }

        enum CollectionMethod
        {
            Pickup,
            Delivery
        }

        #endregion




    }
}

STS/Views/Shipments/Details.cshtml
@model STS.ViewModels.ShipmentDetailsViewModel
@using STS.Resources.Views
@{
    ViewBag.Title = Shipments.ShipmentDetailsTitle;
}
<h2>@ViewBag.Title</h2>
<br />
<br />
<div class="form-group">
    @Html.LabelFor(m => m.TrackingNumber) <br />
    <text class="text-muted">@Model.TrackingNumber</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.DateAdded) <br />
    <text class="text-muted">@Model.DateAdded</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.ArrivalDate) <br />
    <text class="text-muted">@Model.ArrivalDate</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.SenderName) <br />
    <text class="text-muted">@Model.SenderName</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.SenderPhoneNumber) <br />
    <text class="text-muted">@Model.SenderPhoneNumber</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.ReceiverName) <br />
    <text class="text-muted">@Model.ReceiverName</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.ReceiverPhoneNumber) <br />
    <text class="text-muted">@Model.ReceiverPhoneNumber</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.WeightKG) <br />
    <text class="text-muted">@Model.WeightKG</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.Description) <br />
    <text class="text-muted">@Model.Description</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.Source) <br />
    <text class="text-muted">@Model.Source</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.Destination) <br />
    <text class="text-muted">@Model.Destination</text>
</div><br />
<div class="form-group">
    @Html.LabelFor(m => m.CollectionMethod) <br />
    <text class="text-muted">@Model.CollectionMethod</text>
</div><br />
@if(Model.CollectionMethod == Shipments.Delivery) {
<div class="form-group">
    @Html.LabelFor(m => m.DeliveryLocationUrl) <br />
    @if (Model.DeliveryLocationUrl != null)
    {
        <a href="@Model.DeliveryLocationUrl" target="_blank">@Shipments.OpenLocation</a>
    }
    else
    {
        <a>@Shipments.HasNotBeenAssignedYet</a>
    }
</div><br />
}
@Html.ActionLink(Shipments.BackToShipmentsButton, "Index", "Shipments", new { @class = "btn btn-primary" })
<button class="btn btn-primary" onclick=Print('BarcodeLabel')>@Shipments.PrintBarcode</button>
<div id="BarcodeLabel" style="display:none;">
    <h1 style="text-align:center">STS</h1>
    <img style="display: block;margin-left: auto;margin-right: auto;width: 60%;" src="@Url.Action("Barcode" , "Shipments" , new { TrackingNumber = Model.TrackingNumber})" />
</div>

STS/Views/Shipments/Index.cshtml
@using STS.Resources.Views
@{
    ViewBag.Title = Shipments.ShipmentsTitle;
}
<br />
<br />
<table id="Shipments" class="table table-bordered table-hover ">
    <thead class="thead-dark">
        <tr>
            <th class="text-center"><i class='fas fa-boxes'></i></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

STS/Views/Shipments/ShipmentForm.cshtml
@model STS.ViewModels.ShipmentFormViewModel
@using STS.Resources.Views
@{
    bool IsNew = Model.TrackingNumber == null;
    string FixErrors = Shipments.FixErrors;
    string ButtonText = IsNew ? Shipments.NewShipmentButtonText : Shipments.UpdateShipmentButtonText;
    ViewBag.Title = IsNew ? Shipments.NewShipmentTitle : Shipments.UpdateShipmentTitle;
}
<h2>@ViewBag.Title</h2>
<br />
@using (Html.BeginForm("Save", "Shipments"))
{
            <div class="form-group">
                 @Html.LabelFor(m => m.SenderName)
                 @Html.TextBoxFor(m => m.SenderName, new { @Class = "form-control" })
                 @Html.ValidationMessageFor(m => m.SenderName)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.SenderPhoneNumber)
                @Html.TextBoxFor(m => m.SenderPhoneNumber, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.SenderPhoneNumber)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.ReceiverName)
                @Html.TextBoxFor(m => m.ReceiverName, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.ReceiverName)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.ReceiverPhoneNumber)
                @Html.TextBoxFor(m => m.ReceiverPhoneNumber, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.ReceiverPhoneNumber)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.WeightKG)
                @Html.TextBoxFor(m => m.WeightKG, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.WeightKG)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.DestinationLocationId)
                @Html.DropDownListFor(m => m.DestinationLocationId, new SelectList(Model.Locations, "Value", "Text"), Shipments.DestinationListDefaultOption, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DestinationLocationId)
            </div><br />
            <div class="form-group">
                @Html.LabelFor(m => m.CollectionMethod)
                @Html.DropDownListFor(m => m.CollectionMethod, new SelectList(Model.CollectionMethods, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CollectionMethod)
            </div><br />

            <div class="form-group">
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description)
            </div><br />
            @Html.HiddenFor(c => c.TrackingNumber)
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-primary">@ButtonText</button>
            }